# Generated by Django 4.1.4 on 2022-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=40)),
                ('plant_pic', models.ImageField(upload_to='')),
                ('season', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
