# Generated by Django 4.1.4 on 2022-12-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_plants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
