# Generated by Django 4.1.4 on 2022-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_plants_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_pic',
            field=models.ImageField(upload_to='static/media/plant_images'),
        ),
    ]
