# Generated by Django 4.1.4 on 2022-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_plant_plant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
