# Generated by Django 4.1.4 on 2022-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_plant_plant_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_id',
            field=models.CharField(default='', max_length=2),
        ),
    ]
