# Generated by Django 4.1.4 on 2022-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_plant_plant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='medicinal_use',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='plant',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cost',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='plant',
            name='season',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil',
            field=models.CharField(default='', max_length=100),
        ),
    ]
