# Generated by Django 4.1.4 on 2022-12-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_plant_plant_name_alter_plant_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
