# Generated by Django 4.1.4 on 2022-12-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_plant_plant_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='lant_descriptionp',
            new_name='plant_descriptionp',
        ),
    ]
