# Generated by Django 4.1.4 on 2022-12-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_plant_descriptionp_plant_plant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cost',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='medicinal_use',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='season',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
